version: '2'

services:
  registry:
    image: registry:2
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    restart: always
